# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [ ]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [ ]:
a = pd.Series([100,200,300,400])

Print a, and data type

In [ ]:
print(a)
print(a.dtype)

0    100
1    200
2    300
3    400
dtype: int64
int64

Using indexing access the element 300 from the series a.

In [ ]:
print(a[2])

300

What are the values of index for series a?

In [ ]:
a.index

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [ ]:
a.index = ['c', 'a', 'b', 'd']

Access the value in the series with index 'd'

In [ ]:
a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [ ]:
print(a.sort_index())

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [ ]:
b = pd.Series([800,450,100], index = ['e', 'f', 'g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [ ]:
a = pd.concat([a, b])

In [ ]:
#print a again after appending b into it
print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [ ]:
# a =
a_sorted = a.sort_values(ascending=False)
print(a_sorted.index)

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [ ]:
df = pd.DataFrame(a)
print(df)

     0
c  100
a  200
b  300
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [ ]:
df.shape

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [ ]:
# yep its same as the series.
df.index

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [ ]:
print(df.head())

     0
c  100
a  200
b  300
d  400
e  800

In [ ]:
print(df.tail())

     0
b  300
d  400
e  800
f  450
g  100

Rename the column of the dataframe as 'points'

In [ ]:
df.columns = ['points']

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [ ]:
#Create fruits array

fruits = np.random.choice(['orange','mango','apple'], 7)
print(fruits)

['apple' 'apple' 'orange' 'orange' 'orange' 'orange' 'apple']

In [ ]:
#Create series fruits out of fruits array

fruits = pd.Series(fruits)
print(fruits)

0     apple
1     apple
2    orange
3    orange
4    orange
5    orange
6     apple
dtype: object

Change the index of fruits to the index of dataframe df

In [ ]:
fruits.index = df.index

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [ ]:
df['fruits'] = fruits
print(df.head())

   points  fruits
c     100   apple
a     200   apple
b     300  orange
d     400  orange
e     800  orange

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [ ]:
d1 = pd.DataFrame({
    'city': ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali' ],
    'Temperature': [15, 22, 20, 26,-2]
})

Print(d1)

In [ ]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [ ]:
d1.shape

(5, 2)

Set city = d1['city']

In [ ]:
city = d1['city']

print city <br>
What is the type of city.

In [ ]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [ ]:
d2 = pd.DataFrame({
    'city': ['Bengalaru','Coimbatore','Srirangam','Pondicherry'],
    'Temperature': [24,35,36,39]
})

print the shape of this dataframe

In [ ]:
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [ ]:
d3 = pd.concat([d1, d2], ignore_index=True)

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [ ]:
d3[d3['Temperature'] <= 20]

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [ ]:

d3[d3['Temperature'] >= 35]

          city  Temperature
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [ ]:
# write function here

def is_ut(x):
    return x in ['Chandigarh', 'Pondicherry', 'Delhi']

d3['is_ut'] = d3['city'].apply(is_ut)

In [ ]:
# print d3
print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
5    Bengalaru           24  False
6   Coimbatore           35  False
7    Srirangam           36  False
8  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [ ]:
# write function here

def c_to_f(temp):
    return (temp * 9/5) + 32

In [ ]:
# check function c_to_f(10)
c_to_f(10)

50.0

In [ ]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [ ]:
d1[d1['city'].isin(['Chandigarh', 'Delhi'])]

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [ ]:

d1[d1['Temperature'].apply(c_to_f) > 90]

Empty DataFrame
Columns: [city, Temperature]
Index: []

Select only the first three rows of the dataframe d1.

In [ ]:
d1.head(3)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [ ]:
d1.iloc[:, -2:]

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

## Groupby

In [ ]:
# Create a dataframe using dictionary of your choice

data = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul'],
    'Age': [22, 23, 24],
    'City': ['Delhi', 'Mumbai', 'Chennai']
})

In [ ]:
# Use Groupby of single column with aggregate sum()

data.groupby('City').sum()

          Name  Age
City
Chennai  Rahul   24
Delhi     Aman   22
Mumbai    Riya   23

In [ ]:
# Use Groupby of single column with aggregate count()

data.groupby('City').count()

         Name  Age
City
Chennai     1    1
Delhi       1    1
Mumbai      1    1

In [ ]:
# Use Groupby of single column with aggregate min() and max()
data.groupby('City').min()

          Name  Age
City
Chennai  Rahul   24
Delhi     Aman   22
Mumbai    Riya   23

In [ ]:

data.groupby('City').max()

          Name  Age
City
Chennai  Rahul   24
Delhi     Aman   22
Mumbai    Riya   23

In [ ]:
# Use Groupby of any 2 columns with aggregate mean()

data.groupby(['City', 'Name']).mean(numeric_only=True)

                Age
City    Name
Chennai Rahul  24.0
Delhi   Aman   22.0
Mumbai  Riya   23.0

In [ ]:
# Use Groupby of any 2 columns with aggregate min() and max()
data.groupby(['City', 'Name']).min()

               Age
City    Name
Chennai Rahul   24
Delhi   Aman    22
Mumbai  Riya    23

In [ ]:
data.groupby(['City', 'Name']).max()

               Age
City    Name
Chennai Rahul   24
Delhi   Aman    22
Mumbai  Riya    23